version: '3.3'

services:
    mongodb:
      image: mongo
      container_name: "mongodb"
      restart: always
      environment: 
        MONGO_DATA_DIR: /data/db
        MONGO_LOG_DIR: /dev/null
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: 123456
      expose:
        - 27017
      ports:
        - 27017:27017
      volumes:
        - ~/Data/Docker/volumes:/data # Map mongodb data to host filesystem
    