version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-287463}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: always
  
  pgadmin:
    image: dpage/pgadmin4
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "cristiano.mrmartins@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "287463"
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "16543:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: